# Check that the project can build
name: Check build

# Check spelling on the 1st day of the month.
# 1st as the first letter of this repo is the 1st letter in the alphabet.
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release --all-features
      #- uses: actions-rs/cargo@v1
      #  with:
      #    command: build
      #    args: --release --all-features

